CC = gcc-5
CFLAGS = -Wall -m32 -L/usr/lib/gcc/x86_64-linux-gnu/5/32
SOURCE = CreteFiltree.c \
		 DetectionCrete.c \
		 F51_Inv.c \
		 MaxI.c \
		 Rms.c \
		 SinCosH1.c \
		 utils.c \
		 comm.c \
		 cssl.c

lib:
	$(CC) $(CFLAGS) -c $(SOURCE)


clean:
	rm *o
